mod_metadata("name", "Improved Bananza")
mod_metadata("author", "Burrnr")
mod_metadata("version", "1.0.1")

jet_binary_replace("game_data/game_project/assets/data/bloon_sets.bloonset", "bloon_sets.bloonset")
jet_binary_replace("game_data/game_project/assets/data/default.gamerules", "default.gamerules")
jet_binary_replace("game_data/game_project/assets/towers/banana_farm/data/banana_farm.tower_blueprint", "banana_farm.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/data/default_private.gamerules", "default_private.gamerules")
jet_binary_replace("game_data/game_project/assets/towers/druid/data/druid_blueprint.tower_blueprint", "druid_blueprint.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/monkey_buccaneer/data/monkey_buccaneer.tower_blueprint", "monkey_buccaneer.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/heli_pilot/data/heli_pilot.tower_blueprint", "heli_pilot.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/sniper_monkey/data/sniper_monkey.tower_blueprint", "sniper_monkey.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/engineer_monkey/data/engineer_monkey.tower_blueprint", "engineer_monkey.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/alchemist/data/alchemist.tower_blueprint", "alchemist.tower_blueprint")